import TopMenu from '@/components/TopMenu'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
  modal: React.ReactNode
}

export default function RootLayout({ children, modal }: RootLayoutProps) {
  const isHome = false;
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopMenu />
        <div className="flex flex-col items-center justify-between min-h-screen gap-6 p-24 px-3 lg:px-8">
          {children}
          {modal}
        </div>
      </body>
    </html>
  )
}
